language: node_js
node_js:
  - "stable"
git:
  depth: 5
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: rematch
      before_script:
        - npm run bootstrap
        - npm run build
      script: npm run test
      after_script:
        - npm run size
        - coveralls < coverage/lcov.info
