name: Rematch CI

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  build_and_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
            node-version: 12
      - uses: actions/cache@v2
        name: Cache node modules
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install
        run: |
          npm ci
          npm run bootstrap
      - name: Build & Testing
        run: |
          npm run build
          npm run test
          npm run lint
          npm run size
    env:
      CI: true
  release-latest:
    runs-on: ubuntu-latest
    needs: build_and_testing
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release latest
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Release latest version of Rematch
        run: npm run release
  release-next:
    runs-on: ubuntu-latest
    needs: build_and_testing
    if: github.ref == 'refs/heads/next'
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release next version
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Release next version of Rematch
        run: npm run release-next