name: Rematch Docs CI

on:
  workflow_dispatch:
  push:
    paths:
      - "docs/**"
      - "website/**"
      - "blog/**"

jobs:
  build_and_testing:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    env:
      CI: true
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          fetch-depth: "0"

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          scope: '@rematch'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --frozen-lockfile --pure-lockfile

      - name: Build & Testing
        run: |
          yarn lint:docs
          yarn build:docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/build
          CLEAN: true